version: '3.8'

services:
  db:
    image: postgres:16
    container_name: resads-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: resads_user
      POSTGRES_PASSWORD: resads_password
      POSTGRES_DB: resads
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: resads-pgadmin
    restart: always
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@resads.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
